### ISSUE TITLE
Cannot access "http://localhost:5000/users/add_building_model/"

### ISSUE THREAD

**Issue by LiPingjiang** [DF-thangld/SketchupOulu#1]
GET /users/add_building_model/  500 INTERNAL SERVER ERROR localhost:5000

jinja2.exceptions.TemplateSyntaxError

jinja2.exceptions.TemplateSyntaxError: unexpected '<'
Traceback (most recent call last)

```
File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1836, in __call__

return self.wsgi_app(environ, start_response)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1820, in wsgi_app

response = self.make_response(self.handle_exception(e))

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1403, in handle_exception

reraise(exc_type, exc_value, tb)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\_compat.py", line 33, in reraise

raise value

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1817, in wsgi_app

response = self.full_dispatch_request()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request

rv = self.handle_user_exception(e)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1381, in handle_user_exception

reraise(exc_type, exc_value, tb)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\_compat.py", line 33, in reraise

raise value

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request

rv = self.dispatch_request()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1461, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "C:\Users\pli\PycharmProjects\SketchupOulu\app\users\decorators.py", line 11, in decorated_function

return f(*args, **kwargs)

File "C:\Users\pli\PycharmProjects\SketchupOulu\app\users\views.py", line 588, in add_building_model

return render_template("users/add_building_model.html", errors=errors)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\templating.py", line 127, in render_template

return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\environment.py", line 851, in get_or_select_template

return self.get_template(template_name_or_list, parent, globals)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\environment.py", line 812, in get_template

return self._load_template(name, self.make_globals(globals))

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\environment.py", line 786, in _load_template

template = self.loader.load(self, name, globals)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\loaders.py", line 125, in load

code = environment.compile(source, name, filename)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\environment.py", line 565, in compile

self.handle_exception(exc_info, source_hint=source_hint)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\environment.py", line 754, in handle_exception

reraise(exc_type, exc_value, tb)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise

raise value.with_traceback(tb)

File "C:\Users\pli\PycharmProjects\SketchupOulu\app\templates\users\add_building_model.html", line 87, in template

{{gettext('Data file (max file size: 10MB)')*<br/>

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\environment.py", line 470, in _parse

return Parser(self, source, name, encode_filename(filename)).parse()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 897, in parse

result = nodes.Template(self.subparse(), lineno=1)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 879, in subparse

rv = self.parse_statement()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 121, in parse_statement

return getattr(self, 'parse_' + self.stream.current.value)()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 231, in parse_block

node.body = self.parse_statements(('name:endblock',), drop_needle=True)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 156, in parse_statements

result = self.subparse(end_tokens)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 871, in subparse

add_data(self.parse_tuple(with_condexpr=True))

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 616, in parse_tuple

args.append(parse())

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 390, in parse_expression

return self.parse_condexpr()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 395, in parse_condexpr

expr1 = self.parse_or()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 408, in parse_or

left = self.parse_and()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 417, in parse_and

left = self.parse_not()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 428, in parse_not

return self.parse_compare()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 432, in parse_compare

expr = self.parse_add()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 454, in parse_add

left = self.parse_sub()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 464, in parse_sub

left = self.parse_concat()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 474, in parse_concat

args = [self.parse_mul()]

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 487, in parse_mul

right = self.parse_div()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 494, in parse_div

left = self.parse_floordiv()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 504, in parse_floordiv

left = self.parse_mod()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 514, in parse_mod

left = self.parse_pow()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 524, in parse_pow

left = self.parse_unary()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 542, in parse_unary

node = self.parse_primary()

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 579, in parse_primary

self.fail("unexpected '%s'" % describe_token(token), token.lineno)

File "C:\Users\pli\AppData\Local\Programs\Python\Python35-32\lib\site-packages\jinja2\parser.py", line 50, in fail

raise exc(msg, lineno, self.name, self.filename)

jinja2.exceptions.TemplateSyntaxError: unexpected '<'
```

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

```
dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```

**Comment by LiPingjiang** [comment]
And it seems the the zip file is uploaded to local. When I run the server on local host and upload a zip, the uploaded model cannot be see from vm0106.fi

**Comment by DF-thangld** [comment]
solved
